apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.secret.backendDbSecretName }}
type: Opaque                          # Generic Secret just key-value   
stringData:                           #we use StringData so no need to convert the string to base64  
  DB_HOST: {{ .Values.backend.env.DB_HOST }}
  DB_PORT: "{{ .Values.backend.env.DB_PORT }}"
  DB_USER: {{ .Values.backend.env.DB_USER }}
  DB_PASS: {{ .Values.backend.env.DB_PASS }}
  DB_NAME: {{ .Values.backend.env.DB_NAME }}
  POSTGRES_USER: {{ .Values.postgres.env.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.postgres.env.POSTGRES_PASSWORD }}
  POSTGRES_DB: {{ .Values.postgres.env.POSTGRES_DB }}

