apiVersion: v1
kind: Secret
metadata:
    name: backend-db-secret
type: Opaque                          # Generic Secret just key-value   
stringData:                           #we use StringData so no need to convert the string to base64  
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_USER: myappuser
  DB_PASS: password
  DB_NAME: myappdb
  POSTGRES_USER: myappuser 
  POSTGRES_PASSWORD: password 
  POSTGRES_DB: myappdb  

